### ISSUE TITLE
Coinswap Dev Sync W2

### ISSUE THREAD

**Issue by mojoX911** [utxo-teleport/.github#2]
# Coinswap Dev Sync W2
:calendar: _Aug 16, 2024 18:00 IST_
:round_pushpin: _Coinswap Discord General Voice Channel_

## Discussion
- [x] V0.1.0 - Sept 30th.
- [x] Integration tests for Taker, Maker and DNS apps.
- [x] Wallet modules specific to Maker and Taker.
- [ ] New GFIs.

## Work Topics:
- [x] Decouple UTXO fetching [#232](https://github.com/citadel-tech/coinswap/pull/232)
- [x] set Current height as locktime for Contract & Funding tx. [#230](https://github.com/citadel-tech/coinswap/pull/230)
- [x] Bye bye tokio [#224](https://github.com/citadel-tech/coinswap/pull/224)
- [x] MacOS Build [#223](https://github.com/citadel-tech/coinswap/pull/223)
- [x] Add send to address [#222](https://github.com/citadel-tech/coinswap/pull/222)
- [x] feat: Add unique identifier for wallet store [#218](https://github.com/citadel-tech/coinswap/pull/218)
- [x] Park: Add the CBF synchronization function [#176](https://github.com/citadel-tech/coinswap/pull/176)
