### ISSUE TITLE
Coinswap Dev Sync W2

### ISSUE THREAD

**Issue by mojoX911** [utxo-teleport/.github#3]
# Coinswap Dev Sync W2
:calendar: _Aug 22, 2024 18:00 IST_
:round_pushpin: _Coinswap Discord General Voice Channel_

## Discussion
- [x] Project Scoping.
- [x] V0.1.0 Targets.
- [x] V0.1.1 Parallel Tasks.

## Work Topics:
- [x] Replacing unwrap with error handling via AppError Issue #239 [#241](https://github.com/citadel-tech/coinswap/pull/241)
- [x] test_dns [#236](https://github.com/citadel-tech/coinswap/pull/236)
- [x] set Current height as locktime for Contract & Funding tx. [#230](https://github.com/citadel-tech/coinswap/pull/230)
- [x] Bye bye tokio [#224](https://github.com/citadel-tech/coinswap/pull/224)
- [x] Add send to address [#222](https://github.com/citadel-tech/coinswap/pull/222)
- [x] feat: Add unique identifier for wallet store [#218](https://github.com/citadel-tech/coinswap/pull/218)
- [x] Park: Add the CBF synchronization function [#176](https://github.com/citadel-tech/coinswap/pull/176)
