### ISSUE TITLE
Coinswap Dev Sync W3

### ISSUE THREAD

**Issue by mojoX911** [utxo-teleport/.github#4]
# Coinswap Dev Sync W3
:calendar: _Aug 29, 2024 18:00 IST_
:round_pushpin: _Coinswap Discord General Voice Channel_

## Discussion
- [x] Cli App testing Framework.
- [x] Cleanup the Unwraps.
- [x] Doc for analyzing Balance.
- [x] IT for Existing Fidelity.
- [x] Decoupling UTXOs from RPC.
- [x] Other minor TODOs.

## Work Topics:
- [x] Fix Code Coverage [#250](https://github.com/citadel-tech/coinswap/pull/250)
- [x] Improving error handling in the market app [#247](https://github.com/citadel-tech/coinswap/pull/247)
- [x] improve: write modified config values back to the maker config.toml file [#246](https://github.com/citadel-tech/coinswap/pull/246)
- [x] refactor get_next_internal_address to give only 1 address [#245](https://github.com/citadel-tech/coinswap/pull/245)
- [x] write integration test for taker cli app. [#244](https://github.com/citadel-tech/coinswap/pull/244)
- [x] Add the dns test [#243](https://github.com/citadel-tech/coinswap/pull/243)
- [x] Handling errors inside App binary using AppError [#241](https://github.com/citadel-tech/coinswap/pull/241)
- [x] set Current height as locktime for Contract & Funding tx. [#230](https://github.com/citadel-tech/coinswap/pull/230)
- [x] feat: Add unique identifier for wallet store [#218](https://github.com/citadel-tech/coinswap/pull/218)
