### ISSUE TITLE
Coinswap Dev Sync W6

### ISSUE THREAD

**Issue by mojoX911** [utxo-teleport/.github#5]
# Coinswap Dev Sync W6
:calendar: _Sept 19, 2024 18:00 IST_
:round_pushpin: _Coinswap Discord General Voice Channel_

## Discussion
- [x] Cli App testing Framework.
- [x] Cleanup the Unwraps.
- [x] Protocol Docs + IT coverage analysis.
- [x] IT for Existing Fidelity.

## Work Topics:
- [x] Check whether given amount is feasible to spend or not. [#265](https://github.com/citadel-tech/coinswap/pull/265)
- [x] ContractTxInfo construction into helper functions in Signature Request Methods [#260](https://github.com/citadel-tech/coinswap/pull/260)
- [x] Improving error handling in the market app [#247](https://github.com/citadel-tech/coinswap/pull/247)
- [x] improve: write modified config values back to the maker config.toml file [#246](https://github.com/citadel-tech/coinswap/pull/246)
- [x] write integration test for taker cli app. [#244](https://github.com/citadel-tech/coinswap/pull/244)
- [x] Add the dns test [#243](https://github.com/citadel-tech/coinswap/pull/243)
- [x] Handling errors inside App binary using AppError [#241](https://github.com/citadel-tech/coinswap/pull/241)
