### ISSUE TITLE
Coinswap Dev Sync W7

### ISSUE THREAD

**Issue by mojoX911** [utxo-teleport/.github#6]
# Coinswap Dev Sync W7
:calendar: _Oct 03, 2024 18:00 IST_
:round_pushpin: _Coinswap Discord General Voice Channel_

## Discussion
- [x] Cli App testing Framework.
- [x] Cleanup the Unwraps.
- [x] Protocol Docs + IT coverage analysis.
- [x] IT for Existing Fidelity.

## Work Topics:
- [x] Improve DNS address book management [#269](https://github.com/citadel-tech/coinswap/pull/269)
- [x] Handle Errors in Apps and DNS Server [#268](https://github.com/citadel-tech/coinswap/pull/268)
- [x] Check whether given amount is feasible to spend or not. [#265](https://github.com/citadel-tech/coinswap/pull/265)
- [x] improve: write modified config values back to the maker config.toml file [#246](https://github.com/citadel-tech/coinswap/pull/246)
- [x] write integration test for taker cli app. [#244](https://github.com/citadel-tech/coinswap/pull/244)
- [x] Add the dns test [#243](https://github.com/citadel-tech/coinswap/pull/243)
