### ISSUE TITLE
Coinswap Dev Sync W8

### ISSUE THREAD

**Issue by mojoX911** [utxo-teleport/.github#7]
# Coinswap Dev Sync W8
:calendar: _Oct 10, 2024 18:00 IST_
:round_pushpin: _Coinswap Discord General Voice Channel_

## Discussion
- [x] Cli App testing Framework.
- [x] Cleanup the Unwraps.
- [x] Protocol Docs + IT coverage analysis.

## Work Topics:
- [x] Makercli testing [WIP][Not ready for review] [#275](https://github.com/citadel-tech/coinswap/pull/275)
- [x] Change Shutdown signalling to atomics [#274](https://github.com/citadel-tech/coinswap/pull/274)
- [x] point to correct license in readme [#273](https://github.com/citadel-tech/coinswap/pull/273)
- [x] Improve DNS address book management [#269](https://github.com/citadel-tech/coinswap/pull/269)
- [x] Handle Errors in Apps and DNS Server [#268](https://github.com/citadel-tech/coinswap/pull/268)
- [x] Check whether given amount is feasible to spend or not. [#265](https://github.com/citadel-tech/coinswap/pull/265)
- [x] improve: write modified config values back to the maker config.toml file [#246](https://github.com/citadel-tech/coinswap/pull/246)
- [x] Add the dns test [#243](https://github.com/citadel-tech/coinswap/pull/243)
