### ISSUE TITLE
Coinswap Dev Sync W10

### ISSUE THREAD

**Issue by mojoX911** [utxo-teleport/.github#8]
# Coinswap Dev Sync W10
:calendar: _Oct 25, 2024 18:00 IST_
:round_pushpin: _Coinswap Discord General Voice Channel_

## Discussion
- [x] Cli App testing Framework.
- [ ] Cleanup the Unwraps.
- [ ] Protocol Docs + IT coverage analysis.

## Work Topics:
- [ ] [WIP] sync maker wallet to check for incoming transactions & improve Maker Fidelity UX #285
- [ ] write tutorial for taker-cli #283
- [ ] Clean config parameters #276
- [ ] Makercli testing [WIP][Not ready for review] #275
- [ ] improve: write modified config values back to the maker config.toml file #246
- [ ] Add the dns test #243
